<a href="https://colab.research.google.com/github/yasinsoylu1997/nlp-skl/blob/main/nlp_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [3]:
products= pd.read_csv('hepsiburada.csv')

In [4]:
products

yildizSayisi  ... yorumDislike
0                  5  ...            4
1                  5  ...            0
2                  5  ...            0
3                  5  ...            0
4                  5  ...            0
...              ...  ...          ...
479237             1  ...            4
479238             5  ...            6
479239             1  ...           27
479240             3  ...            3
479241             1  ...           29

[479242 rows x 4 columns]

In [5]:
len(products) - len(products.dropna())


0

In [6]:
len(products)


479242

In [7]:
products = products.dropna()


In [8]:
for i in range(0,len(products)-1):
    if type(products.iloc[i]['yorum']) != str:
        products.iloc[i]['yorum'] = str(products.iloc[i]['yorum'])

In [9]:
products = products[products['yildizSayisi'] != 3]


In [10]:
def sentiment(n):
    return 1 if n >= 4 else 0
products['sentiment'] = products['yildizSayisi'].apply(sentiment)
products.head()

yildizSayisi  ... sentiment
0             5  ...         1
1             5  ...         1
2             5  ...         1
3             5  ...         1
4             5  ...         1

[5 rows x 5 columns]

In [11]:
X = products['yorum']
y = products['sentiment']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
ctmTr = cv.fit_transform(X_train)
X_test_dtm = cv.transform(X_test)

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression()
model.fit(ctmTr, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [15]:
y_pred_class = model.predict(X_test_dtm)
y_pred_class

array([1, 1, 1, ..., 1, 1, 1])

In [16]:
accuracy_score(y_test, y_pred_class)


0.9739729722674232

In [17]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred_class))

              precision    recall  f1-score   support

           0       0.85      0.64      0.73      6363
           1       0.98      0.99      0.99    108556

    accuracy                           0.97    114919
   macro avg       0.92      0.82      0.86    114919
weighted avg       0.97      0.97      0.97    114919



In [18]:
from sklearn.naive_bayes import MultinomialNB
model2=MultinomialNB()
model2.fit(ctmTr, y_train)

MultinomialNB()

In [19]:
y_pred2_class = model2.predict(X_test_dtm)
y_pred2_class

array([1, 1, 1, ..., 1, 1, 1])

In [20]:
accuracy_score(y_test, y_pred2_class)


0.9650536464814348

In [21]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred2_class))

              precision    recall  f1-score   support

           0       0.73      0.59      0.65      6363
           1       0.98      0.99      0.98    108556

    accuracy                           0.97    114919
   macro avg       0.85      0.79      0.82    114919
weighted avg       0.96      0.97      0.96    114919



In [22]:
from sklearn.linear_model import SGDClassifier
model3=SGDClassifier()
model3.fit(ctmTr, y_train)

SGDClassifier()

In [23]:
y_pred3_class = model3.predict(X_test_dtm)
y_pred3_class

array([1, 1, 1, ..., 1, 1, 1])

In [24]:
accuracy_score(y_test, y_pred3_class)


0.9682820073268998

In [25]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred3_class))

              precision    recall  f1-score   support

           0       0.88      0.49      0.63      6363
           1       0.97      1.00      0.98    108556

    accuracy                           0.97    114919
   macro avg       0.93      0.74      0.81    114919
weighted avg       0.97      0.97      0.96    114919



In [26]:
from sklearn.linear_model import LogisticRegression
model4=LogisticRegression()
model4.fit(ctmTr, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [27]:
y_pred4_class = model4.predict(X_test_dtm)
y_pred4_class

array([1, 1, 1, ..., 1, 1, 1])

In [28]:
accuracy_score(y_test, y_pred4_class)


0.9739729722674232